# cointegration

Use the "Run" button to execute the code.

In [36]:
jovian.commit(project="cointegration")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "kaustavsen16/cointegration" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/kaustavsen16/cointegration


'https://jovian.ai/kaustavsen16/cointegration'

In [8]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from pandas import DataFrame
import pathlib
from urllib.request import urlretrieve
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
from statsmodels.tsa.api import VAR, VECM
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.vector_ar.vecm import coint_johansen,select_coint_rank

In [3]:
datainddf = pd.read_csv('DATASHEET.csv')
datainddf

YEAR  LAB_SHARE  inv_share  log_gdp_capita
0   1980     38.500   3.025565        9.949954
1   1981     37.800   2.910870        9.985044
2   1982     38.500   2.906384        9.995924
3   1983     38.400   2.901579       10.043075
4   1984     39.600   2.913217       10.057612
5   1985     39.700   2.938682       10.086223
6   1986     40.600   2.927267       10.110673
7   1987     41.300   3.012120       10.127722
8   1988     39.800   3.036231       10.198175
9   1989     39.900   3.056615       10.234838
10  1990     39.800   3.174096       10.267935
11  1991     39.400   2.983069       10.258051
12  1992     39.100   3.051244       10.291393
13  1993     36.400   3.027602       10.318100
14  1994     36.600   3.141089       10.363134
15  1995     37.700   3.143002       10.416958
16  1996     36.700   3.079270       10.470787
17  1997     38.100   3.178290       10.491795
18  1998     38.000   3.155378       10.533405
19  1999     38.800   3.233032       10.600111
20  2000     38.320   3.138499       10.620121
21  2001     37.700   3.136039       10.649945
22  2002     36.800   3.171587       10.670384
23  2003     35.500   3.241789       10.729536
24  2004     30.700   3.426158       10.789630
25  2005     29.900   3.500463       10.850085
26  2006     28.780   3.548472       10.912151
27  2007     28.800   3.641437       10.970875
28  2008     31.100   3.557381       10.986626
29  2009     31.750   3.640863       11.048202
30  2010     31.500   3.691028       11.116256
31  2011     30.380   3.678587       11.154457
32  2012     30.440   3.667504       11.195269
33  2013     30.330   3.567828       11.245345
34  2014     30.844   3.570463       11.305373
35  2015     30.230   3.539748       11.371131
36  2016     30.490   3.496503       11.439557
37  2017     30.760   3.533643       11.494668
38  2018     30.970   3.563352       11.546831

In [4]:
datainddf.index = pd.date_range(start ="1979",end ="2018",freq='A')

In [5]:
datainddf=datainddf.drop(["YEAR"], axis=1)

In [6]:
def joh_output(res):
    output = pd.DataFrame([res.lr2,res.lr1],
                          index=['max_eig_stat',"trace_stat"])
    print(output.T,'\n')
    print("Critical values(90%, 95%, 99%) of max_eig_stat\n",res.cvm,'\n')
    print("Critical values(90%, 95%, 99%) of trace_stat\n",res.cvt,'\n')
 

In [7]:
# Model 3 (2 lag-difference used = 3 lags VAR or VAR(3) model)
# with constant/trend (deterministc) term
joh_model3 = coint_johansen(datainddf,0,4) # k_ar_diff +1 = K
joh_output(joh_model3)
# Model 2: with linear trend only
joh_model2 = coint_johansen(datainddf,1,4) # k_ar_diff +1 = K
joh_output(joh_model2)
 
# Model 1: no constant/trend (deterministc) term
joh_model1 = coint_johansen(datainddf,-1,4) # k_ar_diff +1 = K
joh_output(joh_model1)

   max_eig_stat  trace_stat
0     24.069991   48.377552
1     15.866700   24.307562
2      8.440861    8.440861 

Critical values(90%, 95%, 99%) of max_eig_stat
 [[18.8928 21.1314 25.865 ]
 [12.2971 14.2639 18.52  ]
 [ 2.7055  3.8415  6.6349]] 

Critical values(90%, 95%, 99%) of trace_stat
 [[27.0669 29.7961 35.4628]
 [13.4294 15.4943 19.9349]
 [ 2.7055  3.8415  6.6349]] 

   max_eig_stat  trace_stat
0     20.706477   33.507928
1      9.123880   12.801451
2      3.677570    3.677570 

Critical values(90%, 95%, 99%) of max_eig_stat
 [[21.8731 24.2522 29.2631]
 [15.0006 17.1481 21.7465]
 [ 2.7055  3.8415  6.6349]] 

Critical values(90%, 95%, 99%) of trace_stat
 [[32.0645 35.0116 41.0815]
 [16.1619 18.3985 23.1485]
 [ 2.7055  3.8415  6.6349]] 

   max_eig_stat  trace_stat
0     22.516951   33.394271
1     10.185107   10.877320
2      0.692212    0.692212 

Critical values(90%, 95%, 99%) of max_eig_stat
 [[15.7175 17.7961 22.2519]
 [ 9.4748 11.2246 15.0923]
 [ 2.9762  4.1296  6.9406]] 

Cr

In [34]:
rank = select_coint_rank(datainddf,0,3, method='maxeig', signif=0.01)
rank.summary()

<class 'statsmodels.iolib.table.SimpleTable'>

In [19]:
datainddf['D_inv_share']=datainddf['inv_share'].diff(1)

In [29]:
adftest = adfuller(datainddf['D_inv_share'].dropna(),autolag="BIC")
print('ADF Statistic: %f' % adftest[0])
print('p-value: %f' % adftest[1])

ADF Statistic: -7.347382
p-value: 0.000000


In [32]:
model = VECM(datainddf, coint_rank=2,k_ar_diff=3)
vecm_res = model.fit()
vecm_res.gamma.round(4)
vecm_res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
Det. terms outside the coint. relation & lagged endog. parameters for equation LAB_SHARE
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
L1.LAB_SHARE          0.0436      0.195      0.224      0.823      -0.338       0.425
L1.inv_share         -4.7178      4.326     -1.091      0.275     -13.196       3.760
L1.log_gdp_capita    11.1975     14.383      0.779      0.436     -16.992      39.387
L2.LAB_SHARE          0.0632      0.199      0.318      0.750      -0.326       0.452
L2.inv_share         -1.4408      4.457     -0.323      0.746     -10.176       7.294
L2.log_gdp_capita    22.7865     14.001      1.628      0.104      -4.655      50.228
L3.LAB_SHARE         -0.0765      0.185     -0.413      0.680      -0.440       0.287
L3.inv_share         -2.2584      3.668     -0.616      0.538      -9.448       4.932
L3.log_gdp_capita    15.5831     13.450      1.159      0.247     -10.779      41.945
Det. terms outside the coint. relation & lagged endog. parameters for equation inv_share
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
L1.LAB_SHARE          0.0027      0.009      0.315      0.753      -0.014       0.020
L1.inv_share          0.3659      0.192      1.902      0.057      -0.011       0.743
L1.log_gdp_capita    -1.6334      0.640     -2.553      0.011      -2.887      -0.380
L2.LAB_SHARE          0.0173      0.009      1.964      0.050    3.77e-05       0.035
L2.inv_share          0.7637      0.198      3.853      0.000       0.375       1.152
L2.log_gdp_capita    -1.5823      0.623     -2.541      0.011      -2.803      -0.362
L3.LAB_SHARE          0.0120      0.008      1.453      0.146      -0.004       0.028
L3.inv_share          0.6455      0.163      3.956      0.000       0.326       0.965
L3.log_gdp_capita    -1.9872      0.598     -3.322      0.001      -3.160      -0.815
Det. terms outside the coint. relation & lagged endog. parameters for equation log_gdp_capita
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
L1.LAB_SHARE          0.0051      0.002      2.060      0.039       0.000       0.010
L1.inv_share          0.1092      0.055      1.999      0.046       0.002       0.216
L1.log_gdp_capita    -0.3179      0.182     -1.751      0.080      -0.674       0.038
L2.LAB_SHARE          0.0026      0.003      1.039      0.299      -0.002       0.008
L2.inv_share          0.1215      0.056      2.160      0.031       0.011       0.232
L2.log_gdp_capita    -0.4327      0.177     -2.448      0.014      -0.779      -0.086
L3.LAB_SHARE         -0.0013      0.002     -0.546      0.585      -0.006       0.003
L3.inv_share          0.0408      0.046      0.881      0.378      -0.050       0.132
L3.log_gdp_capita    -0.4358      0.170     -2.566      0.010      -0.769      -0.103
             Loading coefficients (alpha) for equation LAB_SHARE              
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ec1            0.1222      0.104      1.180      0.238      -0.081       0.325
ec2            1.8290      3.633      0.503      0.615      -5.292       8.950
             Loading coefficients (alpha) for equation inv_share              
===============================